### ISSUE TITLE
Init Problem - missing module?

### ISSUE THREAD

**Issue by batoub** [davidb24v/meross-utils#1]
Hi,

I have a strange problem with your program (missing module?) : 

Traceback (most recent call last):
  File "meross", line 12, in <module>
    import meross_powermon.command_line as command_line
  File "/home/bastien/Meross/meross_powermon/command_line.py", line 10, in <module>
    from meross_powermon import (config, delete, init, monitor, setup)
  File "/home/bastien/Meross/meross_powermon/config.py", line 9, in <module>
    from meross_powermon.modified_device import Mss310
  File "/home/bastien/Meross/meross_powermon/modified_device.py", line 15, in <module>
    from meross_iot.supported_devices.power_plugs import (Device, ClientStatus)
ModuleNotFoundError: No module named 'meross_iot.supported_devices'

Is there any solution?
Best Regards,
Bastien

**Comment by harphere** [comment]
@batoub,did you ever solve that error? 

EDIT: Found the fix through another forum: run `pip3 install meross_iot==0.1.4.3` after running `setup.py`

**Comment by kusannaghi** [comment]
when i execute setup.py i have the next error:

root@rpi3-20210209:/home/pi/meross_powermon# python3 ./setup.py
Traceback (most recent call last):
  File "./setup.py", line 11, in <module>
    from meross_powermon import (iwlist, config)
ModuleNotFoundError: No module named 'meross_powermon'

And don't work. Anybody know what happen ??
